Repository RandomKiddo/ChocolateMod, pull requests merged in 2023-01, with the labels that each got.

#12 Copyright for 2023
  src/main/java/io/github/randomkiddo/Chocolate.java
  src/main/java/io/github/randomkiddo/ChocolateClient.java
  src/main/java/io/github/randomkiddo/armor/ArmorRegistry.java
  src/main/java/io/github/randomkiddo/armor/EmeraldMaterial.java
  src/main/java/io/github/randomkiddo/blocks/BlockRegistry.java
  src/main/java/io/github/randomkiddo/chocolates/ChocolateRegistry.java
  src/main/java/io/github/randomkiddo/effects/FreezeStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/NullifyStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/NumbStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/PotionsRegistry.java
  src/main/java/io/github/randomkiddo/effects/StatusEffectsRegistry.java
  src/main/java/io/github/randomkiddo/enchants/AdrenalineEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/AquaAspectEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/EnchantmentRegistry.java
  src/main/java/io/github/randomkiddo/enchants/ExperienceEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/LightweightEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/VampireEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/WinceEnchantment.java
  src/main/java/io/github/randomkiddo/fluids/AcidFluid.java
  src/main/java/io/github/randomkiddo/fluids/FluidRegistry.java
  src/main/java/io/github/randomkiddo/mixin/CloudTrunkPlacerTypeInvoker.java
  src/main/java/io/github/randomkiddo/mixin/InAcidMixin.java
  src/main/java/io/github/randomkiddo/ores/IngotRegistry.java
  src/main/java/io/github/randomkiddo/ores/OreRegistry.java
  src/main/java/io/github/randomkiddo/worldgen/BiomeModificationsRegistry.java
  src/main/java/io/github/randomkiddo/worldgen/CloudSaplingBlock.java
  src/main/java/io/github/randomkiddo/worldgen/CloudSaplingGenerator.java
  src/main/java/io/github/randomkiddo/worldgen/CloudTrunkPlacer.java
  src/main/java/io/github/randomkiddo/worldgen/TreeRegistry.java
Labels: enhancement, ignore

#14 Numb Status Effect on rk1
  src/main/java/io/github/randomkiddo/effects/NumbStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/PotionsRegistry.java
  src/main/java/io/github/randomkiddo/effects/StatusEffectsRegistry.java
  src/main/java/io/github/randomkiddo/mixin/NumbDamageTrackerMixin.java
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/textures/mob_effect/numb.png
  src/main/resources/chocolate.mixins.json
Labels: enhancement

#15 Update AdrenalineEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/AdrenalineEnchantment.java
Labels: documentation

#16 Update Copyrights for 2023 - No. 2
  src/main/java/io/github/randomkiddo/Chocolate.java
  src/main/java/io/github/randomkiddo/ChocolateClient.java
  src/main/java/io/github/randomkiddo/armor/ArmorRegistry.java
  src/main/java/io/github/randomkiddo/armor/EmeraldMaterial.java
  src/main/java/io/github/randomkiddo/blocks/BlockRegistry.java
  src/main/java/io/github/randomkiddo/chocolates/ChocolateRegistry.java
  src/main/java/io/github/randomkiddo/effects/FreezeStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/NullifyStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/NumbStatusEffect.java
  src/main/java/io/github/randomkiddo/effects/PotionsRegistry.java
  src/main/java/io/github/randomkiddo/effects/StatusEffectsRegistry.java
  src/main/java/io/github/randomkiddo/enchants/AdrenalineEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/AquaAspectEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/EnchantmentRegistry.java
  src/main/java/io/github/randomkiddo/enchants/ExperienceEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/LightweightEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/VampireEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/WinceEnchantment.java
  src/main/java/io/github/randomkiddo/fluids/AcidFluid.java
  src/main/java/io/github/randomkiddo/fluids/FluidRegistry.java
  src/main/java/io/github/randomkiddo/mixin/CloudTrunkPlacerTypeInvoker.java
  src/main/java/io/github/randomkiddo/mixin/InAcidMixin.java
  src/main/java/io/github/randomkiddo/mixin/NumbDamageTrackerMixin.java
  src/main/java/io/github/randomkiddo/ores/IngotRegistry.java
  src/main/java/io/github/randomkiddo/ores/OreRegistry.java
  src/main/java/io/github/randomkiddo/tools/FoseliumMaterial.java
  src/main/java/io/github/randomkiddo/tools/FoseliumPickaxeItem.java
  src/main/java/io/github/randomkiddo/tools/ToolRegistry.java
  src/main/java/io/github/randomkiddo/worldgen/BiomeModificationsRegistry.java
  src/main/java/io/github/randomkiddo/worldgen/CloudSaplingBlock.java
  src/main/java/io/github/randomkiddo/worldgen/CloudSaplingGenerator.java
  src/main/java/io/github/randomkiddo/worldgen/CloudTrunkPlacer.java
  src/main/java/io/github/randomkiddo/worldgen/TreeRegistry.java
Labels: ignore

#19 Fixed Milk Chocolate loot tables and added Dark Chocolate blocks.
  src/main/java/io/github/randomkiddo/blocks/BlockRegistry.java
  src/main/resources/assets/chocolate/blockstates/dark_chocolate.json
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/block/dark_chocolate.json
  src/main/resources/assets/chocolate/models/item/dark_chocolate.json
  src/main/resources/assets/chocolate/textures/block/dark_chocolate.png
  src/main/resources/data/chocolate/loot_tables/blocks/dark_chocolate.json
  src/main/resources/data/chocolate/loot_tables/blocks/milk_chocolate.json
Labels: enhancement

#22 Fix Cloud Leaves Rendering Error
  src/main/java/io/github/randomkiddo/armor/SlimeMaterial.java
  src/main/java/io/github/randomkiddo/blocks/BlockRegistry.java
Labels: bug, client side

#24 Added Chocolate Milk
  src/main/java/io/github/randomkiddo/ChocolateClient.java
  src/main/java/io/github/randomkiddo/fluids/ChocolateMilkFluid.java
  src/main/java/io/github/randomkiddo/fluids/FluidRegistry.java
  src/main/java/io/github/randomkiddo/mixin/InChocolateMilkMixin.java
  src/main/resources/assets/chocolate/blockstates/chocolate_milk,json
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/block/chocolate_milk.json
  src/main/resources/assets/chocolate/models/item/chocolate_milk_bucket.json
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_flow.png
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_flow.png.mcmeta
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_still.png
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_still.png.mcmeta
  src/main/resources/assets/chocolate/textures/item/chocolate_milk_bucket.png
  src/main/resources/chocolate.mixins.json
  src/main/resources/data/minecraft/tags/fluids/water.json
Labels: enhancement, help wanted

#25 Master to SoapLiquid Merge
  src/main/java/io/github/randomkiddo/ChocolateClient.java
  src/main/java/io/github/randomkiddo/fluids/ChocolateMilkFluid.java
  src/main/java/io/github/randomkiddo/fluids/FluidRegistry.java
  src/main/java/io/github/randomkiddo/mixin/InChocolateMilkMixin.java
  src/main/resources/assets/chocolate/blockstates/chocolate_milk,json
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/block/chocolate_milk.json
  src/main/resources/assets/chocolate/models/item/chocolate_milk_bucket.json
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_flow.png
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_flow.png.mcmeta
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_still.png
  src/main/resources/assets/chocolate/textures/block/chocolate_milk_still.png.mcmeta
  src/main/resources/assets/chocolate/textures/item/chocolate_milk_bucket.png
  src/main/resources/chocolate.mixins.json
  src/main/resources/data/minecraft/tags/fluids/water.json
Labels: ignore, outdated

#27 Acid Corrosion Resistance Enchantment
  src/main/java/io/github/randomkiddo/enchants/CorrosionResistanceEnchantment.java
  src/main/java/io/github/randomkiddo/enchants/EnchantmentRegistry.java
  src/main/java/io/github/randomkiddo/mixin/InLiquidMixin.java
  src/main/resources/assets/chocolate/lang/en_us.json
Labels: enhancement

#28 README Collaborator Additions
  README.md
Labels: documentation, ignore

#29 Soap Liquid
  src/main/java/io/github/randomkiddo/Chocolate.java
  src/main/java/io/github/randomkiddo/items/ItemRegistry.java
  src/main/resources/assets/chocolate/blockstates/chocolate_milk.json
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/item/soap.json
  src/main/resources/assets/chocolate/textures/item/soap.png
  src/main/resources/data/chocolate/recipes/soap_bucket_item.json
  src/main/resources/data/chocolate/recipes/soap_item.json
Labels: bug, enhancement

#30 Fast v Fancy Graphics Config
  src/main/java/io/github/randomkiddo/Chocolate.java
  src/main/java/io/github/randomkiddo/ChocolateClient.java
  src/main/java/io/github/randomkiddo/config/ConfigProvider.java
  src/main/java/io/github/randomkiddo/config/ConfigRegistry.java
  src/main/java/io/github/randomkiddo/config/MainConfig.java
Labels: enhancement

#31 Chocolate Tools + Other Fixes
  src/main/java/io/github/randomkiddo/config/ConfigProvider.java
  src/main/java/io/github/randomkiddo/config/ConfigRegistry.java
  src/main/java/io/github/randomkiddo/config/MainConfig.java
  src/main/java/io/github/randomkiddo/tools/ChocolateAxeItem.java
  src/main/java/io/github/randomkiddo/tools/ChocolateHoeItem.java
  src/main/java/io/github/randomkiddo/tools/ChocolateMaterial.java
  src/main/java/io/github/randomkiddo/tools/ChocolatePickaxeItem.java
  src/main/java/io/github/randomkiddo/tools/ToolRegistry.java
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/item/chocolate_axe.json
  src/main/resources/assets/chocolate/models/item/chocolate_hoe.json
  src/main/resources/assets/chocolate/models/item/chocolate_pickaxe.json
  src/main/resources/assets/chocolate/models/item/chocolate_shovel.json
  src/main/resources/assets/chocolate/models/item/chocolate_sword.json
  src/main/resources/assets/chocolate/textures/item/chocolate_axe.png
  src/main/resources/assets/chocolate/textures/item/chocolate_hoe.png
  src/main/resources/assets/chocolate/textures/item/chocolate_pickaxe.png
  src/main/resources/assets/chocolate/textures/item/chocolate_shovel.png
  src/main/resources/assets/chocolate/textures/item/chocolate_sword.png
  src/main/resources/data/chocolate/recipes/chocolate_axe.json
  src/main/resources/data/chocolate/recipes/chocolate_axe_inverted.json
  src/main/resources/data/chocolate/recipes/chocolate_hoe.json
  src/main/resources/data/chocolate/recipes/chocolate_hoe_inverted.json
  src/main/resources/data/chocolate/recipes/chocolate_pickaxe.json
  src/main/resources/data/chocolate/recipes/chocolate_shovel.json
  src/main/resources/data/chocolate/recipes/chocolate_sword.json
Labels: enhancement

#32 Chocolate Armor Commit
  src/main/java/io/github/randomkiddo/armor/ArmorRegistry.java
  src/main/java/io/github/randomkiddo/armor/ChocolateMaterial.java
  src/main/java/io/github/randomkiddo/mixin/PlayerFallDamageMixin.java
  src/main/java/io/github/randomkiddo/mixin/PlayerHungerDropsMixin.java
  src/main/resources/assets/chocolate/lang/en_us.json
  src/main/resources/assets/chocolate/models/item/chocolate_boots.json
  src/main/resources/assets/chocolate/models/item/chocolate_chestplate.json
  src/main/resources/assets/chocolate/models/item/chocolate_helmet.json
  src/main/resources/assets/chocolate/models/item/chocolate_leggings.json
  src/main/resources/assets/chocolate/textures/item/chocolate_boots.png
  src/main/resources/assets/chocolate/textures/item/chocolate_chestplate.png
  src/main/resources/assets/chocolate/textures/item/chocolate_helmet.png
  src/main/resources/assets/chocolate/textures/item/chocolate_leggings.png
  src/main/resources/assets/minecraft/textures/models/armor/chocolate_layer_1.png
  src/main/resources/assets/minecraft/textures/models/armor/chocolate_layer_2.png
  src/main/resources/chocolate.mixins.json
  src/main/resources/data/chocolate/recipes/chocolate_boots_item.json
  src/main/resources/data/chocolate/recipes/chocolate_chestplate_item.json
  src/main/resources/data/chocolate/recipes/chocolate_helmet_item.json
  src/main/resources/data/chocolate/recipes/chocolate_leggings_item.json
Labels: enhancement
